# Site settings
title: "Rebekah Johanna Terry"
description: "Rebekah J. Terry is a hard-working and adaptable Operations Specialist with strong management and communication skills with a drive to ensure high-quality and consistent work."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Rebekah Johanna Terry"
resume_title:                   "Operations Specialist"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "rebekahj.terry@gmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "(770) 653-6874"
resume_contact_address:         "Herndon, VA"

resume_header_contact_info:     "Herndon, VA • (770) 653-6874 • <a href='mailto:rebekahj.terry@gmail.com'>rebekahj.terry@gmail.com</a>"
display_header_contact_info:    "true"

resume_header_intro: "<p>Hard-working and adaptable Operations Specialist with strong management and communication skills with a drive to ensure high-quality and consistent work.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        false
resume_section_skills:          true
resume_section_recognition:     false
resume_section_links:           false
resume_section_associations:    false
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  # resume_github_url:            "https://github.com/jglovier/resume-template"
  # resume_twitter_url:           "http://twitter.com/jglovier"
  # resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/rebekahjterry"
  # resume_instagram_url:         "insert your Instagram URL here"
  resume_website_url:           "https://rebekahjterry.com"
  # resume_medium_url:            "https://medium.com/@jglovier"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
